### ISSUE TITLE
Dynamic properties management

### ISSUE THREAD

**Issue by rvencu** [bmhm/wordpress-jsonld-plugin#7]
Caching is very good idea to improve speed but there is need to handle dynamic properties such as:
- commentCount
- comment
- aggregateRating
- review

**Comment by bmarwell** [comment]
Yeah, I'd like to update it with some kind of frequency or have a more intelligent change detection. I'm open to suggestions.

Like:
1. update at least every xx min
2. find a hook for new comments and just remove the cache file
3. anything else

solution 2 is probably the most sane one. See: https://codex.wordpress.org/Plugin_API/Action_Reference/comment_post

The only thing we need to figure out is how to get the post id from the comment id.

**Comment by rvencu** [comment]
Solution 2 is easy, there is a comment_post_ID in the comment object and is indeed the most sane idea.

You need to account also for https://codex.wordpress.org/Function_Reference/wp_update_comment if the moderator approves the comment sometimes later.

I would also create some API in this plugin for other developers that want to create some other interactions with the articles, so the action to empty the JSONLD cache can be triggered from outside as well.

For instance as Article supports aggregateRating I just made a simple rating form using Formidable plugin and added rating average for every post and page like this one:

http://www.dentfix.ro/servicii/parodontologie/ So I would like to clear the JSONLD cache also when a new rating is saved

**Comment by bmarwell** [comment]
I think we can use the cache API. If users have a caching plugin installed, it should work automatically for plugins and page changes. If not, output will be dynamic. 
https://codex.wordpress.org/Class_Reference/WP_Object_Cache

I'm not sure if those rating systems do clear the cache for given pages. If so, we are lucky. If not, we would pull lots of dependencies, which I don't really like.

**Comment by rvencu** [comment]
Seems reasonable to use existing WordPress API. Everyone should do so and
you can just document it in readme file for other developers.

On Thu, Dec 31, 2015 at 10:48 AM, Ben notifications@github.com wrote:

> I think we can use the cache API. If users have a caching plugin
> installed, it should work automatically for plugins and page changes. If
> not, output will be dynamic.
> https://codex.wordpress.org/Class_Reference/WP_Object_Cache
> 
> I'm not sure if those rating systems do clear the cache for given pages.
> If so, we are lucky. If not, we would pull lots of dependencies, which I
> don't really like.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bmhm/wp-jsonld/issues/7#issuecomment-168152393.

## 

Richard

**Comment by bmarwell** [comment]
Note to self: use this instead: http://codex.wordpress.org/Transients_API

**Comment by bmarwell** [comment]
Working test, see:
https://github.com/bmhm/wp-jsonld/commit/dcf3e26a065d64e73342454068a9041c060bde99
https://github.com/bmhm/wp-jsonld/commit/846136e097d866972eeb7d1d9911fe6ec00e1f43
https://github.com/bmhm/wp-jsonld/commit/f7740e7dbd3ee22543dbe761b283696b21c84154

Search your database in table "wp_options" for keys like "_transient_wp-jsonld_%".
